---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-attachments
  namespace: {{ .Release.Namespace }}
  labels:
    app: attachments
spec:
  selector:
    matchLabels:
      app: attachments
  template:
    metadata:
      labels:
        app: attachments
        release: attachments
    spec:
      restartPolicy: Always
      containers:
      - name: attachments
        image: bitwarden/attachments:2022.9.2
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
        env:
          - name: globalSettings__sqlServer__connectionString
            valueFrom:
              secretKeyRef:
                name: globalsettings--sqlserver
                key: connectionString
                optional: false
          - name: globalSettings__mail__smtp__username
            valueFrom:
              secretKeyRef:
                name: globalsettings--mail--smtp
                key: username
                optional: false
          - name: globalSettings__mail__smtp__password
            valueFrom:
              secretKeyRef:
                name: globalsettings--mail--smtp
                key: password
                optional: false
          - name: globalSettings__installation__id
            valueFrom:
              secretKeyRef:
                name: globalsettings--installation
                key: id
                optional: false
          - name: globalSettings__installation__key
            valueFrom:
              secretKeyRef:
                name: globalsettings--installation
                key: key
                optional: false
          - name: globalSettings__identityServer__certificatePassword
            valueFrom:
              secretKeyRef:
                name: globalsettings--identityserver
                key: certificatePassword
                optional: false
          - name: globalSettings__internalIdentityKey
            valueFrom:
              secretKeyRef:
                name: globalsettings--internalidentitykey
                key: value
                optional: false
          - name: globalSettings__oidcIdentityClientKey
            valueFrom:
              secretKeyRef:
                name: globalsettings--oidcidentityclientkey
                key: value
                optional: false
          - name: globalSettings__duo__aKey
            valueFrom:
              secretKeyRef:
                name: globalsettings--duo--akey
                key: value
                optional: false
        volumeMounts:
          - mountPath: /etc/bitwarden/core/attachments
            name: {{ .Release.Name }}-attachments-pvc
      volumes:
        - name: {{ .Release.Name }}-attachments-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-attachments-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-attachments-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-attachments
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
