---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notifications
  namespace: {{ .Release.Namespace }}
  labels:
    app: notifications
spec:
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
        release: notifications
    spec:
      restartPolicy: Always
      containers:
      - name: notifications
        image: bitwarden/notifications:2022.9.2
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
        env:
          - name: globalSettings__sqlServer__connectionString
            valueFrom:
              secretKeyRef:
                name: globalsettings--sqlserver
                key: connectionString
                optional: false
          - name: globalSettings__mail__smtp__username
            valueFrom:
              secretKeyRef:
                name: globalsettings--mail--smtp
                key: username
                optional: false
          - name: globalSettings__mail__smtp__password
            valueFrom:
              secretKeyRef:
                name: globalsettings--mail--smtp
                key: password
                optional: false
          - name: globalSettings__installation__id
            valueFrom:
              secretKeyRef:
                name: globalsettings--installation
                key: id
                optional: false
          - name: globalSettings__installation__key
            valueFrom:
              secretKeyRef:
                name: globalsettings--installation
                key: key
                optional: false
          - name: globalSettings__identityServer__certificatePassword
            valueFrom:
              secretKeyRef:
                name: globalsettings--identityserver
                key: certificatePassword
                optional: false
          - name: globalSettings__internalIdentityKey
            valueFrom:
              secretKeyRef:
                name: globalsettings--internalidentitykey
                key: value
                optional: false
          - name: globalSettings__oidcIdentityClientKey
            valueFrom:
              secretKeyRef:
                name: globalsettings--oidcidentityclientkey
                key: value
                optional: false
          - name: globalSettings__duo__aKey
            valueFrom:
              secretKeyRef:
                name: globalsettings--duo--akey
                key: value
                optional: false
        volumeMounts:
          - mountPath: /etc/ssl/bitwarden/ca
            name: bitwarden-ca
          - mountPath: /etc/ssl/bitwarden/client
            name: bitwarden-client
      volumes:
        - name: bitwarden-ca
          secret:
            secretName: bitwarden-ca
        - name: bitwarden-client
          secret:
            secretName: bitwarden-client
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifications
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: notifications
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
