---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        release: web
    spec:
      restartPolicy: Always
      containers:
      - name: web
        image: bitwarden/web:2022.9.2
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: web
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
